#!/bin/bash

export CONTAINER_ROOT="${CONTAINER_ROOT:-'/var/srv/containers'}"
source "${CONTAINER_ROOT}/.bin/rc.bash"

if [[ $# -lt 1 ]] ; then
    printf 'Usage: %s <CONTAINER_NAME> [command]\n' "${0}"
    exit 1
fi

CONTAINER_NAME="${1}"
shift

if [[ $# -lt 1 ]] ; then
    "${CM_CMD}" exec -it -- $(container_name_safe_str ${CONTAINER_NAME}) /bin/bash
else
    "${CM_CMD}" exec -it -- $(container_name_safe_str ${CONTAINER_NAME}) $*
fi
