#!/bin/bash

export CONTAINER_ROOT="${CONTAINER_ROOT:-'/var/srv/containers'}"
source "${CONTAINER_ROOT}/.bin/rc.bash"

if [[ $# -ne 1 ]] ; then
    printf 'Usage: %s <CONTAINER_NAME>\n' "${0}"
    exit 1
fi

CONTAINER_NAME="${1}"
shift

pdestroy "${CONTAINER_NAME}"
pstart "${CONTAINER_NAME}"
