#!/bin/bash

export CONTAINER_ROOT="${CONTAINER_ROOT:-'/var/srv/containers'}"
source "${CONTAINER_ROOT}/.bin/rc.bash"

if [[ $# -ne 1 ]]; then
    printf "Usage: %s CONTAINER_NAME\n" "${0}"
    exit 1
fi

CONTAINER_NAME="${1}"
shift

"${CM_CMD}" start "${CONTAINER_NAME}"

# Exit code 125 means there was no container with that name (podman)
# but it is exit code 1 for docker
exit_code=$?
if [[ $exit_code -eq 125 ]] || [[ $exit_code -eq 1 ]] ; then
    pcreate "${CONTAINER_NAME}"
    "${CM_CMD}" start "$(container_name_safe_str ${CONTAINER_NAME})"
else
    printf '%s: FATAL: got unexpected exit code (%s)\n' "${0}" "${exit_code}"
fi
